### ISSUE TITLE
Payment status detected as 'fail' even when provider has accepted payment

### ISSUE THREAD

**Issue by niklasmannila** [CheckoutFinland/checkout-finland-php-sdk#16]
**Description**
Checkout returns 'fail'-status even when the provider (bank) has received a payment if the user closes the browser too early or re-opens transaction for payment after bank has received the payment.

**To Reproduce**
This can be reproduced with the test credentials provided by CheckoutFinland using the following steps:

1. Create a new payment
2. Fill in bank security details and code (we used Nordea for testing)
3. Once the payment is finished, close the browser before the page is automatically redirected to the redirect url provided during payment.
4. Check the payment status using the getPaymentStatus method and it will return status as 'new' at this point.
5. Try to complete the payment chain by using the href provided in the PaymentStatusResponse (https://pay.checkout.fi/pay/[UUID])
6. The bank notifies that payment is already received, press the link to return to the seller.

The result is that checkout redirects with a fail status. See GET result below:
`
[checkout-account] => 375917
[checkout-algorithm] => sha256
[checkout-amount] => 2200
[checkout-stamp] => 3f823dfa-3d1e-11ea-a676-00163ea2afb8
[checkout-reference] => 266
[checkout-transaction-id] => 3fd1f854-3d1e-11ea-bd18-4bdc473f2988
[checkout-status] => fail
[checkout-provider] => nordea
`
Notice that 'checkout-status' is 'fail'.

**Expected behavior**
Ideally the status would get updated correctly already after step 3. But at the least it should recognize that the payment has been completed after step 6.

**Additional context**
I realize that it may be difficult for you to know what has happend on the provider page if the user closes the window too eagerly. But at least the latter case should be possible to identify?

**Comment by loueranta** [comment]
@niklasmannila The "fail" status is actually correct as you are trying to complete the already completed payment. 

If the customer fails to return from the bank, the getPaymentStatus will update to reflect the successful payment only after our system has polled the bank for payment status. Polling happens every 15 minutes, so it's not immediately updated on the getPaymentStatus.

**Comment by Ahtoranta** [comment]
Hi.
Here is a little clarification to why we just show fail on second try :

As we never get the information that the payment was succeeded from the bank (step 3 above) the payment on our system will naturally stay at state 'new'.

Now when the payment is tried to be paid again the bank immediately responds with page telling 'payment already exists in our system' or something like that but we cannot see that reason. From that page the end user is redirected to our cancel url and there is no reason or explanation, it is just success or cancel. And thus we do not get success we cannot do anything else than left the payment as new and respond with fail.
As Joonas said the system automatically polls the payments afterwards from payment providers and confirms/updates the payment statuses. Also merchants redirect/callback urls are called when poller updates payments paid so polling the payment status is not necessary. Depending on provider it can take anything from 15 min to 2 days to get the status updated.

Hopefully this clarifies the flow. The redirection from the bank to our system is essential part of a "real time" payment flow.

P.s. payments created with test accounts are not polled afterwards, only the payments with accounts and real money are involved.

**Comment by niklasmannila** [comment]
Sorry for the late reply, I have been on a 2 week vacation. Thanks for the additional information regarding this issue. But it still seems like the payment does not stay as 'new' if the customer happens to re-open the payment link that has already been registered as paid to the bank. The payment status stays as 'new' until the customer re-visits the payment link and after the prompt is shown that payment is already received and the customer clicks the "Return to seller" link the checkout payment status changes to 'fail' and will stay that way (at least with test credentials).

My test scenario:
1. The customer starts payment 
2. Picks a bank and enters banking credentials
3. Closes window after successful payment without returning to our page
4. Polling payment status now returns 'new' (which is good)
5. The pending payment is visible in our system and offers the option to complete the payment
6. The customer clicks the link because we do not have info about the transaction actually being successful and the state is still 'new'
7. Banking page notifies the customer that payment is already registered and follows the link to the seller page
8. At this point the payment status has now changed to 'fail' both for the redirect url and for the payment status polling.

Did you mean that this would still return 'new' in production and this is only a test credential issue? 
If this happens in all environments it would mean that we can no longer offer the "continue payment" option to our customers since it would make the payment fail. I fail to understand why the payment is left as 'new' but then still responds with 'fail'? Wouldn't that mean that in production the status of the payment could be 'new', then 'fail' (if the customer tries to complete payment that is already paid) and then 'ok' once you poll the bank and figure out everything is fine...?

Might be that there is some aspect of this that I do not fully understand yet but to me it seems like the customer can "corrupt" a successful sale just by visiting that payment link a second time? The only option we have in this case is to make sure that the customer does not find out how to re-visit the transaction link.

Sorry for commenting on a closed issue, not sure what the correct way is for asking further questions on this issue otherwise.
